FROM Python:3.13-slim

WORKDIR /app

#Install Requirements
COPY requirements.txt .
RUN pip install --no-cahce-dir -r requirements.txt

#Copy Project
COPY app ./app

#Expose Gunicorn Port
EXPOSE 8000

#Start Gunicorn
CMD ["gunicorn", "-b", "0.0.0.0:8000", "wsgi:app", "--chdir", "app"]